//! C*-algebra generated by evolution operator.
//!
//! For an evolution operator T, the C*-algebra C*(T) is the smallest
//! C*-algebra containing T. This algebra encodes all spectral information
//! about the dynamics.

use nalgebra::{DMatrix, DVector, ComplexField};
use num_complex::Complex64;
use serde::{Deserialize, Serialize};

/// An element of the C*-algebra (a bounded operator represented as a matrix).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlgebraElement {
    matrix: DMatrix<f64>,
}

impl AlgebraElement {
    /// Create from a matrix.
    pub fn new(matrix: DMatrix<f64>) -> Self {
        Self { matrix }
    }

    /// Get the matrix.
    pub fn matrix(&self) -> &DMatrix<f64> {
        &self.matrix
    }

    /// Compute the adjoint (conjugate transpose = transpose for real matrices).
    pub fn adjoint(&self) -> Self {
        Self {
            matrix: self.matrix.transpose(),
        }
    }

    /// Compute the operator norm (largest singular value).
    pub fn norm(&self) -> f64 {
        // Singular values via eigenvalues of A^T A
        let ata = &self.matrix.transpose() * &self.matrix;
        let n = ata.nrows();
        if n == 0 {
            return 0.0;
        }

        // Power iteration for largest eigenvalue of A^T A
        let mut v = DVector::from_element(n, 1.0 / (n as f64).sqrt());
        for _ in 0..200 {
            let w = &ata * &v;
            let norm = w.iter().map(|x| x * x).sum::<f64>().sqrt();
            if norm < 1e-15 {
                return 0.0;
            }
            v = w / norm;
        }
        let lambda = (&v.transpose() * &ata * &v)[(0, 0)];
        lambda.sqrt()
    }

    /// Add two algebra elements.
    pub fn add(&self, other: &AlgebraElement) -> AlgebraElement {
        AlgebraElement {
            matrix: &self.matrix + &other.matrix,
        }
    }

    /// Multiply two algebra elements.
    pub fn mul(&self, other: &AlgebraElement) -> AlgebraElement {
        AlgebraElement {
            matrix: &self.matrix * &other.matrix,
        }
    }

    /// Scale by a scalar.
    pub fn scale(&self, c: f64) -> AlgebraElement {
        AlgebraElement {
            matrix: self.matrix.scale(c),
        }
    }
}

/// C*-algebra generated by evolution operators.
///
/// Contains the evolution operator T and is closed under:
/// - Addition
/// - Multiplication (composition)
/// - Scalar multiplication
/// - Adjoint (involution)
/// - Norm limits
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CStarAlgebra {
    /// Generator matrices of the algebra
    generators: Vec<AlgebraElement>,
    /// Dimension of the underlying space
    dimension: usize,
}

impl CStarAlgebra {
    /// Create a C*-algebra from a single evolution operator.
    pub fn from_generator(generator: DMatrix<f64>) -> Self {
        let dim = generator.nrows();
        Self {
            generators: vec![AlgebraElement::new(generator)],
            dimension: dim,
        }
    }

    /// Create from multiple generators.
    pub fn from_generators(generators: Vec<DMatrix<f64>>) -> Self {
        let dim = generators.first().map_or(0, |m| m.nrows());
        Self {
            generators: generators.into_iter().map(AlgebraElement::new).collect(),
            dimension: dim,
        }
    }

    /// Get the dimension.
    pub fn dimension(&self) -> usize {
        self.dimension
    }

    /// Get the generators.
    pub fn generators(&self) -> &[AlgebraElement] {
        &self.generators
    }

    /// Compute the identity element.
    pub fn identity(&self) -> AlgebraElement {
        AlgebraElement::new(DMatrix::identity(self.dimension, self.dimension))
    }

    /// Compute the adjoint of a generator.
    pub fn generator_adjoint(&self, idx: usize) -> AlgebraElement {
        self.generators[idx].adjoint()
    }

    /// Check if an element is self-adjoint (A = A*).
    pub fn is_self_adjoint(element: &AlgebraElement, tol: f64) -> bool {
        let diff = element.matrix() - element.adjoint().matrix();
        diff.iter().all(|x| x.abs() < tol)
    }

    /// Check if an element is positive (all eigenvalues ≥ 0).
    pub fn is_positive(element: &AlgebraElement, tol: f64) -> bool {
        // A is positive iff A = B*B for some B, or equivalently all eigenvalues ≥ 0
        let n = element.matrix().nrows();
        if n == 0 {
            return true;
        }

        // Check via eigenvalues of the symmetric part
        let sym = (element.matrix() + &element.adjoint().matrix()).scale(0.5);
        let ata = &sym.transpose() * &sym;

        // Power iteration to find smallest eigenvalue
        let mut v = DVector::from_element(n, 1.0 / (n as f64).sqrt());
        for _ in 0..200 {
            let w = &ata * &v;
            let norm = w.iter().map(|x| x * x).sum::<f64>().sqrt();
            if norm < 1e-15 {
                return true;
            }
            v = w / norm;
        }
        let lambda = (&v.transpose() * &ata * &v)[(0, 0)];
        lambda >= -tol
    }

    /// Compute the spectrum (approximate) of an algebra element.
    pub fn spectrum(element: &AlgebraElement, num_points: usize) -> Vec<Complex64> {
        let n = element.matrix().nrows();
        if n == 0 {
            return Vec::new();
        }

        // Approximate eigenvalues via iterative method
        let mut eigenvalues = Vec::new();
        let mut mat = element.matrix().clone();

        for _ in 0..num_points.min(n) {
            let mut v = DVector::from_element(n, 1.0 / (n as f64).sqrt());
            let mut eigenvalue = 0.0f64;

            for _ in 0..300 {
                let w = &mat * &v;
                let norm = w.iter().map(|x| x * x).sum::<f64>().sqrt();
                if norm < 1e-15 {
                    break;
                }
                v = w / norm;
                eigenvalue = (&v.transpose() * &mat * &v)[(0, 0)];
            }

            eigenvalues.push(Complex64::new(eigenvalue, 0.0));
            let v_outer = &v * &v.transpose();
            mat = &mat - eigenvalue * v_outer;
        }

        eigenvalues
    }

    /// Compute the spectral radius of an element.
    pub fn spectral_radius(element: &AlgebraElement) -> f64 {
        let spec = Self::spectrum(element, element.matrix().nrows());
        spec.iter().map(|z| z.norm()).fold(0.0f64, f64::max)
    }

    /// Compute the C*-norm of an element (equals spectral radius for self-adjoint).
    pub fn c_star_norm(element: &AlgebraElement) -> f64 {
        element.norm()
    }

    /// Check if the algebra is commutative (all generators commute).
    pub fn is_commutative(&self, tol: f64) -> bool {
        for i in 0..self.generators.len() {
            for j in (i + 1)..self.generators.len() {
                let commutator = self.generators[i].mul(&self.generators[j])
                    .add(&self.generators[j].mul(&self.generators[i]).scale(-1.0));
                if commutator.norm() > tol {
                    return false;
                }
            }
        }
        true
    }

    /// Generate polynomials in the generator up to degree d.
    pub fn polynomial_closure(&self, max_degree: usize) -> Vec<AlgebraElement> {
        if self.generators.is_empty() {
            return Vec::new();
        }

        let gen = &self.generators[0];
        let mut elements = vec![self.identity(), gen.clone()];

        for d in 2..=max_degree {
            let last = elements.last().unwrap();
            elements.push(last.mul(gen));
        }

        elements
    }

    /// Compute the commutator [A, B] = AB - BA.
    pub fn commutator(a: &AlgebraElement, b: &AlgebraElement) -> AlgebraElement {
        a.mul(b).add(&b.mul(a).scale(-1.0))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;

    #[test]
    fn test_algebra_element_norm() {
        let m = DMatrix::from_vec(2, 2, vec![3.0, 0.0, 0.0, 4.0]);
        let elem = AlgebraElement::new(m);
        assert_relative_eq!(elem.norm(), 4.0, epsilon = 1e-8);
    }

    #[test]
    fn test_adjoint() {
        let m = DMatrix::from_vec(2, 2, vec![1.0, 2.0, 3.0, 4.0]);
        let elem = AlgebraElement::new(m);
        let adj = elem.adjoint();
        assert_relative_eq!(adj.matrix()[(0, 1)], 2.0, epsilon = 1e-10);
        assert_relative_eq!(adj.matrix()[(1, 0)], 3.0, epsilon = 1e-10);
    }

    #[test]
    fn test_self_adjoint() {
        let m = DMatrix::from_vec(2, 2, vec![1.0, 2.0, 2.0, 3.0]);
        let elem = AlgebraElement::new(m);
        assert!(CStarAlgebra::is_self_adjoint(&elem, 1e-10));
    }

    #[test]
    fn test_not_self_adjoint() {
        let m = DMatrix::from_vec(2, 2, vec![1.0, 3.0, 2.0, 4.0]);
        let elem = AlgebraElement::new(m);
        assert!(!CStarAlgebra::is_self_adjoint(&elem, 1e-10));
    }

    #[test]
    fn test_positive_element() {
        let m = DMatrix::from_vec(2, 2, vec![2.0, 0.0, 0.0, 3.0]);
        let elem = AlgebraElement::new(m);
        assert!(CStarAlgebra::is_positive(&elem, 0.1));
    }

    #[test]
    fn test_c_star_algebra_from_generator() {
        let gen = DMatrix::from_vec(2, 2, vec![0.5, 0.5, 0.5, 0.5]);
        let algebra = CStarAlgebra::from_generator(gen);
        assert_eq!(algebra.dimension(), 2);
    }

    #[test]
    fn test_commutative_check() {
        let gen = DMatrix::identity(3, 3);
        let algebra = CStarAlgebra::from_generator(gen);
        assert!(algebra.is_commutative(1e-10));
    }

    #[test]
    fn test_commutator() {
        let a = AlgebraElement::new(DMatrix::from_vec(2, 2, vec![0.0, 0.0, 1.0, 0.0]));
        let b = AlgebraElement::new(DMatrix::from_vec(2, 2, vec![0.0, 1.0, 0.0, 0.0]));
        let comm = CStarAlgebra::commutator(&a, &b);
        // [σ_x, σ_y] should be non-zero
        assert!(comm.norm() > 0.1);
    }

    #[test]
    fn test_polynomial_closure() {
        let gen = DMatrix::from_vec(2, 2, vec![0.5, 0.5, 0.5, 0.5]);
        let algebra = CStarAlgebra::from_generator(gen);
        let polys = algebra.polynomial_closure(3);
        assert_eq!(polys.len(), 4); // identity + degree 1, 2, 3
    }

    #[test]
    fn test_spectrum() {
        let m = DMatrix::from_vec(2, 2, vec![2.0, 0.0, 0.0, 3.0]);
        let elem = AlgebraElement::new(m);
        let spec = CStarAlgebra::spectrum(&elem, 2);
        assert_eq!(spec.len(), 2);
        // Should contain eigenvalues 2 and 3
        let norms: Vec<f64> = spec.iter().map(|z| z.re).collect();
        assert!(norms.iter().any(|&n| (n - 3.0).abs() < 0.1));
    }

    #[test]
    fn test_spectral_radius() {
        let m = DMatrix::from_vec(2, 2, vec![2.0, 0.0, 0.0, 3.0]);
        let elem = AlgebraElement::new(m);
        let r = CStarAlgebra::spectral_radius(&elem);
        assert_relative_eq!(r, 3.0, epsilon = 0.1);
    }

    #[test]
    fn test_add_elements() {
        let a = AlgebraElement::new(DMatrix::identity(2, 2));
        let b = AlgebraElement::new(DMatrix::identity(2, 2));
        let c = a.add(&b);
        assert_relative_eq!(c.matrix()[(0, 0)], 2.0);
    }

    #[test]
    fn test_scale_element() {
        let a = AlgebraElement::new(DMatrix::identity(2, 2));
        let b = a.scale(3.0);
        assert_relative_eq!(b.matrix()[(0, 0)], 3.0);
    }
}
