//! C\*-algebra generated by evolution
//!
//! Defines the algebraic structure arising from composing evolution operators.
//! The C\*-algebra generated by a dynamical system captures spectral information
//! through Gelfand duality and crossed product constructions.

use nalgebra::DMatrix;
use num_complex::Complex;
use serde::{Deserialize, Serialize};

/// An element of the operator algebra, represented as a matrix.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlgebraElement {
    matrix: DMatrix<Complex<f64>>,
}

impl AlgebraElement {
    /// Create from a complex matrix.
    pub fn new(matrix: DMatrix<Complex<f64>>) -> Self {
        Self { matrix }
    }

    /// Create from a real matrix.
    pub fn from_real(matrix: DMatrix<f64>) -> Self {
        Self {
            matrix: matrix.map(|x| Complex::new(x, 0.0)),
        }
    }

    /// Create the identity element.
    pub fn identity(n: usize) -> Self {
        Self {
            matrix: DMatrix::identity(n, n),
        }
    }

    /// Create the zero element.
    pub fn zero(n: usize) -> Self {
        Self {
            matrix: DMatrix::zeros(n, n),
        }
    }

    /// Dimension.
    pub fn dim(&self) -> usize {
        self.matrix.nrows()
    }

    /// Get the underlying matrix.
    pub fn matrix(&self) -> &DMatrix<Complex<f64>> {
        &self.matrix
    }

    /// C\*-norm (operator norm, approximated by spectral radius of A\*A).
    pub fn cstar_norm(&self) -> f64 {
        let a_star_a = self.adjoint().matrix.clone() * &self.matrix;
        spectral_radius_complex(&a_star_a).sqrt()
    }

    /// Adjoint (conjugate transpose).
    pub fn adjoint(&self) -> Self {
        Self {
            matrix: self.matrix.adjoint(),
        }
    }

    /// Trace.
    pub fn trace(&self) -> Complex<f64> {
        self.matrix.trace()
    }

    /// Check if self-adjoint (Hermitian).
    pub fn is_self_adjoint(&self, tol: f64) -> bool {
        let adj = self.adjoint();
        let n = self.dim();
        for i in 0..n {
            for j in 0..n {
                let diff = self.matrix[(i, j)] - adj.matrix[(i, j)];
                if diff.norm() > tol {
                    return false;
                }
            }
        }
        true
    }

    /// Check if positive semi-definite.
    pub fn is_positive(&self, tol: f64) -> bool {
        if !self.is_self_adjoint(tol) {
            return false;
        }
        // Check via eigenvalues (simplified: check trace and determinant signs)
        let n = self.dim();
        if n == 0 {
            return true;
        }
        // For small matrices, check principal minors
        for k in 1..=n {
            let mut sub = DMatrix::zeros(k, k);
            for i in 0..k {
                for j in 0..k {
                    sub[(i, j)] = self.matrix[(i, j)].re;
                }
            }
            if sub.determinant() < -tol {
                return false;
            }
        }
        true
    }

    /// Add two algebra elements.
    pub fn add(&self, other: &Self) -> Self {
        Self {
            matrix: &self.matrix + &other.matrix,
        }
    }

    /// Multiply two algebra elements.
    pub fn mul(&self, other: &Self) -> Self {
        Self {
            matrix: &self.matrix * &other.matrix,
        }
    }

    /// Scalar multiplication.
    pub fn scale(&self, c: Complex<f64>) -> Self {
        Self {
            matrix: self.matrix.map(|x| x * c),
        }
    }
}

/// The C\*-algebra generated by an evolution operator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvolutionAlgebra {
    /// The generator (evolution operator).
    generator: AlgebraElement,
    /// Dimension.
    dim: usize,
}

impl EvolutionAlgebra {
    /// Create the C\*-algebra generated by the given evolution operator.
    pub fn new(generator: AlgebraElement) -> Self {
        let dim = generator.dim();
        Self { generator, dim }
    }

    /// Get the generator.
    pub fn generator(&self) -> &AlgebraElement {
        &self.generator
    }

    /// Compute the n-th power of the generator.
    pub fn power(&self, n: usize) -> AlgebraElement {
        if n == 0 {
            AlgebraElement::identity(self.dim)
        } else {
            let mut result = self.generator.clone();
            for _ in 1..n {
                result = result.mul(&self.generator);
            }
            result
        }
    }

    /// Compute polynomial in the generator: Σ c_k * A^k.
    pub fn polynomial(&self, coefficients: &[Complex<f64>]) -> AlgebraElement {
        let mut result = AlgebraElement::zero(self.dim);
        for (k, &c) in coefficients.iter().enumerate() {
            let term = self.power(k).scale(c);
            result = result.add(&term);
        }
        result
    }

    /// Compute the commutator [A, B] = AB - BA.
    pub fn commutator(a: &AlgebraElement, b: &AlgebraElement) -> AlgebraElement {
        a.mul(b).add(&b.mul(a).scale(Complex::new(-1.0, 0.0)))
    }

    /// Check if the algebra is commutative (generator is normal).
    pub fn is_commutative(&self, tol: f64) -> bool {
        let comm = Self::commutator(&self.generator, &self.generator.adjoint());
        let n = comm.dim();
        for i in 0..n {
            for j in 0..n {
                if comm.matrix()[(i, j)].norm() > tol {
                    return false;
                }
            }
        }
        true
    }

    /// Compute the spectral radius of the generator.
    pub fn spectral_radius(&self) -> f64 {
        self.generator.cstar_norm()
    }

    /// Functional calculus: evaluate f at the generator using polynomial approximation.
    /// For a polynomial f, this is exact.
    pub fn functional_calculus_poly(&self, coeffs: &[Complex<f64>]) -> AlgebraElement {
        self.polynomial(coeffs)
    }
}

/// Approximate spectral radius of a complex matrix.
fn spectral_radius_complex(mat: &DMatrix<Complex<f64>>) -> f64 {
    let n = mat.nrows();
    if n == 0 {
        return 0.0;
    }
    // Power iteration for dominant eigenvalue
    let mut v = nalgebra::DVector::from_element(n, Complex::new(1.0 / (n as f64).sqrt(), 0.0));
    for _ in 0..500 {
        let v_new = mat * &v;
        let norm = v_new.map(|c| c.norm()).norm();
        if norm < 1e-20 {
            return 0.0;
        }
        v = v_new.map(|c| c * (1.0 / norm));
    }
    let av = mat * &v;
    // Rayleigh quotient
    let num: Complex<f64> = v.iter().zip(av.iter()).map(|(a, b)| a.conj() * b).sum();
    let den: f64 = v.iter().map(|c| c.norm().powi(2)).sum();
    if den.abs() < 1e-20 {
        0.0
    } else {
        (num / den).norm()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;

    #[test]
    fn test_identity_norm() {
        let e = AlgebraElement::identity(3);
        assert_relative_eq!(e.cstar_norm(), 1.0, epsilon = 1e-8);
    }

    #[test]
    fn test_self_adjoint() {
        let m = DMatrix::from_row_slice(2, 2, &[1.0, 2.0, 2.0, 3.0]);
        let e = AlgebraElement::from_real(m);
        assert!(e.is_self_adjoint(1e-10));
    }

    #[test]
    fn test_not_self_adjoint() {
        let m = DMatrix::from_row_slice(2, 2, &[1.0, 2.0, 3.0, 4.0]);
        let e = AlgebraElement::from_real(m);
        assert!(!e.is_self_adjoint(1e-10));
    }

    #[test]
    fn test_positive() {
        let m = DMatrix::from_row_slice(2, 2, &[2.0, 0.0, 0.0, 3.0]);
        let e = AlgebraElement::from_real(m);
        assert!(e.is_positive(1e-10));
    }

    #[test]
    fn test_not_positive() {
        let m = DMatrix::from_row_slice(2, 2, &[-1.0, 0.0, 0.0, 1.0]);
        let e = AlgebraElement::from_real(m);
        assert!(!e.is_positive(1e-10));
    }

    #[test]
    fn test_commutative_algebra() {
        // Diagonal matrix commutes with everything
        let gen = AlgebraElement::from_real(DMatrix::from_diagonal(&nalgebra::DVector::from_vec(vec![1.0, 2.0])));
        let alg = EvolutionAlgebra::new(gen);
        assert!(alg.is_commutative(1e-10));
    }

    #[test]
    fn test_evolution_power() {
        let gen = AlgebraElement::from_real(DMatrix::from_row_slice(2, 2, &[2.0, 0.0, 0.0, 3.0]));
        let alg = EvolutionAlgebra::new(gen);
        let p3 = alg.power(3);
        assert_relative_eq!(p3.matrix()[(0, 0)].re, 8.0, epsilon = 1e-10);
        assert_relative_eq!(p3.matrix()[(1, 1)].re, 27.0, epsilon = 1e-10);
    }

    #[test]
    fn test_adjoint() {
        let m = DMatrix::from_row_slice(2, 2, &[1.0, 2.0, 3.0, 4.0]);
        let e = AlgebraElement::from_real(m);
        let adj = e.adjoint();
        assert_relative_eq!(adj.matrix()[(0, 1)].re, 3.0, epsilon = 1e-10);
        assert_relative_eq!(adj.matrix()[(1, 0)].re, 2.0, epsilon = 1e-10);
    }

    #[test]
    fn test_trace() {
        let e = AlgebraElement::from_real(DMatrix::from_row_slice(2, 2, &[1.0, 2.0, 3.0, 4.0]));
        assert_relative_eq!(e.trace().re, 5.0, epsilon = 1e-10);
    }
}
