//! # lau-dynamical-algebra
//!
//! The algebra of dynamical systems — operator algebras from evolution.
//!
//! This crate provides mathematical tools for studying dynamical systems through
//! the lens of operator algebras, spectral theory, and thermodynamic formalism.
//!
//! ## Modules
//!
//! - [`transfer`] — Transfer operator (Perron-Frobenius)
//! - [`koopman`] — Koopman operator
//! - [`cstar`] — C\*-algebra generated by evolution
//! - [`spectral`] — Spectral decomposition
//! - [`zeta`] — Dynamical zeta function det(I − zT)⁻¹
//! - [`thermo`] — Thermodynamic formalism (pressure, equilibrium)
//! - [`ruelle`] — Ruelle operator
//! - [`subshift`] — Subshift of finite type
//! - [`entropy`] — Entropy of dynamical systems
//! - [`lyapunov`] — Lyapunov spectrum via Oseledets theorem

pub mod transfer;
pub mod koopman;
pub mod cstar;
pub mod spectral;
pub mod zeta;
pub mod thermo;
pub mod ruelle;
pub mod subshift;
pub mod entropy;
pub mod lyapunov;

pub use nalgebra::{DMatrix, DVector, ComplexField};
pub use num_complex::Complex;
